---
# Jobs development containers

services:
  api:
    image: jobs/api:latest
    build:
      context: ./api
      x-bake:
        cache-from:
          - type=local,src=.docker_cache
        cache-to:
          - type=local,dest=.docker_cache
    ports:
      - 8000:80
    depends_on:
      - db
    volumes:
      - ./db:/code/db
    networks:
      - frontend
      - backend
    environment:
      POSTGRES_HOST: host.docker.internal
      POSTGRES_PORT: 5432
      POSTGRES_DB_NAME: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    extra_hosts:
      - "host.docker.internal:host-gateway"
  
  frontend:
    image: jobs/frontend:latest
    build:
      context: ./frontend
      x-bake:
        cache-from:
          - type=local,src=.docker_cache
        cache-to:
          - type=local,dest=.docker_cache
    ports:
      - 8001:80
    networks:
      - frontend

  nlu:
    image: jobs/nlu:latest
    build:
      context: ./nlu
      x-bake:
        cache-from:
          - type=local,src=.docker_cache
        cache-to:
          - type=local,dest=.docker_cache
    ports:
      - 8002:5005
    networks:
      - backend

  worker:
    image: jobs/worker:latest
    build:
      context: ./worker
      x-bake:
        cache-from:
          - type=local,src=.docker_cache
        cache-to:
          - type=local,dest=.docker_cache
    command: worker
    environment:
      CELERY_BACKEND: redis://redis:6379/0
    depends_on:
      - redis
    networks:
      - backend

  beat:
    image: jobs/worker:latest
    command: beat
    environment:
      CELERY_BACKEND: redis://redis:6379/0
    depends_on:
      - redis
    networks:
      - backend

  db:
    image: ankane/pgvector:v0.4.4
    container_name: jobs-db
    ports:
      - 5432:5432
    networks:
      - backend

  redis:
    image: redis:alpine
    container_name: jobs-redis
    ports:
      - 6379:6379
    networks:
      - backend

  selenium:
    image: selenium/standalone-chrome:latest
    container_name: jobs-selenium
    environment:
      SE_NODE_SESSION_TIMEOUT: 250
      SE_NODE_MAX_SESSIONS: 3
      START_XVFB: "false"
    shm_size: 2gb
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - 4444:4444
    networks:
      - backend

networks:
  frontend:
  backend:
